In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
with open("D:\\ML_PROJECT\\NSL_KDD-master\\Field Names_1.csv") as f:
    columns = [line.strip() for line in f]
test = pd.read_csv("D:\\ML_PROJECT\\NSL_KDD-master\\KDDTest+.csv" , names=columns)
train = pd.read_csv("D:\\ML_PROJECT\\NSL_KDD-master\\KDDTrain+.csv" , names=columns)

In [4]:
train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [5]:
data = pd.concat([train, test], axis=0, ignore_index=True)

In [6]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

In [7]:
data.shape

(148516, 43)

In [8]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [9]:
le = LabelEncoder()
scaler = StandardScaler()

In [10]:
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le.fit_transform(data[col])

In [11]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,1,20,9,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,16,20
1,0,2,44,9,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,16,15
2,0,1,49,5,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,14,19
3,0,1,24,9,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,16,21
4,0,1,24,9,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,16,21

In [13]:
counts = data['label'].value_counts()
print(counts)

label
16    77053
14    45871
25     4368
7      3740
27     3311
20     3088
15     1566
1      1315
4      1284
11      996
35      964
32      904
34      890
0       737
21      685
29      331
24      319
10      293
19      242
28      178
5       133
2        50
8        25
12       25
23       23
13       17
22       15
26       14
39       13
6        12
3        11
9        11
37        9
18        6
17        5
38        4
30        2
36        2
31        2
33        2
Name: count, dtype: int64

In [12]:
data['label'][data['label'] == 16] = 1
data['label'][data['label'] != 1] = -1

In [13]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty
0,0,1,20,9,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1,20
1,0,2,44,9,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1,15
2,0,1,49,5,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,-1,19
3,0,1,24,9,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1,21
4,0,1,24,9,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1,21

In [14]:
data = data.drop(columns='difficulty')

In [15]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,1,20,9,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1
1,0,2,44,9,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1
2,0,1,49,5,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,-1
3,0,1,24,9,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1
4,0,1,24,9,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1

In [16]:
scaler = StandardScaler()
data.iloc[:,:-1] = scaler.fit_transform(data.iloc[:,:-1])

In [17]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,-0.112481,-0.132004,-0.719822,0.733738,-0.007346,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.849247,-0.813562,-0.278724,0.077993,-0.280651,-0.597722,-0.584815,-0.267147,-0.406816,1
1,-0.112481,2.236001,0.753355,0.733738,-0.007409,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-1.065013,-1.192976,2.657933,2.378450,-0.280651,-0.597722,-0.584815,-0.422070,-0.406816,1
2,-0.112481,-0.132004,1.060267,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.840257,-0.969791,-0.175684,-0.472820,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1
3,-0.112481,-0.132004,-0.474293,0.733738,-0.007394,-0.002413,-0.01468,-0.085488,-0.010403,-0.094071,...,1.218504,1.038871,-0.433285,-0.375618,0.086406,-0.527711,-0.561544,-0.422070,-0.376991,1
4,-0.112481,-0.132004,-0.474293,0.733738,-0.007400,-0.004501,-0.01468,-0.085488,-0.010403,-0.094071,...,1.218504,1.038871,-0.433285,-0.472820,-0.280651,-0.597722,-0.584815,-0.422070,-0.406816,1

In [18]:
data_normal = data[data['label'] == 1]
data_anomaly = data[data['label'] == -1]

In [19]:
data_normal.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,-0.112481,-0.132004,-0.719822,0.733738,-0.007346,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.849247,-0.813562,-0.278724,0.077993,-0.280651,-0.597722,-0.584815,-0.267147,-0.406816,1
1,-0.112481,2.236001,0.753355,0.733738,-0.007409,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-1.065013,-1.192976,2.657933,2.378450,-0.280651,-0.597722,-0.584815,-0.422070,-0.406816,1
3,-0.112481,-0.132004,-0.474293,0.733738,-0.007394,-0.002413,-0.01468,-0.085488,-0.010403,-0.094071,...,1.218504,1.038871,-0.433285,-0.375618,0.086406,-0.527711,-0.561544,-0.422070,-0.376991,1
4,-0.112481,-0.132004,-0.474293,0.733738,-0.007400,-0.004501,-0.01468,-0.085488,-0.010403,-0.094071,...,1.218504,1.038871,-0.433285,-0.472820,-0.280651,-0.597722,-0.584815,-0.422070,-0.406816,1
12,-0.112481,-0.132004,-0.474293,0.733738,-0.007383,-0.004006,-0.01468,-0.085488,-0.010403,-0.094071,...,0.894856,1.038871,-0.433285,-0.084011,-0.005358,-0.597722,-0.584815,-0.422070,-0.406816,1

In [20]:
data_anomaly.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
2,-0.112481,-0.132004,1.060267,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.840257,-0.969791,-0.175684,-0.47282,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1
5,-0.112481,-0.132004,1.060267,-2.149201,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.903189,-1.036747,-0.072643,-0.47282,-0.280651,-0.597722,-0.584815,2.676392,2.575746,-1
6,-0.112481,-0.132004,1.060267,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.993091,-1.103702,-0.175684,-0.47282,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1
7,-0.112481,-0.132004,1.060267,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.939150,-1.059065,-0.072643,-0.47282,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1
8,-0.112481,-0.132004,1.183032,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.867228,-0.992110,-0.175684,-0.47282,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1

In [21]:
data_train = data_normal[:52000]
data_train.shape

(52000, 42)

In [27]:
data_test = np.concat([data_anomaly[:25633] , data_normal[52001 :]])
data_test = pd.DataFrame(data_test , columns=data.columns)
data_test.shape

(52000, 42)

In [28]:
data_train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,-0.112481,-0.132004,-0.719822,0.733738,-0.007346,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.849247,-0.813562,-0.278724,0.077993,-0.280651,-0.597722,-0.584815,-0.267147,-0.406816,1
1,-0.112481,2.236001,0.753355,0.733738,-0.007409,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-1.065013,-1.192976,2.657933,2.378450,-0.280651,-0.597722,-0.584815,-0.422070,-0.406816,1
3,-0.112481,-0.132004,-0.474293,0.733738,-0.007394,-0.002413,-0.01468,-0.085488,-0.010403,-0.094071,...,1.218504,1.038871,-0.433285,-0.375618,0.086406,-0.527711,-0.561544,-0.422070,-0.376991,1
4,-0.112481,-0.132004,-0.474293,0.733738,-0.007400,-0.004501,-0.01468,-0.085488,-0.010403,-0.094071,...,1.218504,1.038871,-0.433285,-0.472820,-0.280651,-0.597722,-0.584815,-0.422070,-0.406816,1
12,-0.112481,-0.132004,-0.474293,0.733738,-0.007383,-0.004006,-0.01468,-0.085488,-0.010403,-0.094071,...,0.894856,1.038871,-0.433285,-0.084011,-0.005358,-0.597722,-0.584815,-0.422070,-0.406816,1

In [29]:
data_test.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,-0.112481,-0.132004,1.060267,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.840257,-0.969791,-0.175684,-0.47282,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1.0
1,-0.112481,-0.132004,1.060267,-2.149201,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.903189,-1.036747,-0.072643,-0.47282,-0.280651,-0.597722,-0.584815,2.676392,2.575746,-1.0
2,-0.112481,-0.132004,1.060267,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.993091,-1.103702,-0.175684,-0.47282,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1.0
3,-0.112481,-0.132004,1.060267,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.939150,-1.059065,-0.072643,-0.47282,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1.0
4,-0.112481,-0.132004,1.183032,-0.707731,-0.007436,-0.004614,-0.01468,-0.085488,-0.010403,-0.094071,...,-0.867228,-0.992110,-0.175684,-0.47282,-0.280651,1.736005,1.742287,-0.422070,-0.406816,-1.0

In [30]:
X_train = data_train.drop(columns=['label'])
y_train = data_train['label']

In [31]:
X_test = data_test.drop(columns=['label'])
y_test = data_test['label']

In [33]:
from sklearn.svm import OneClassSVM
from sklearn.metrics import classification_report

In [34]:
model = OneClassSVM(nu= 0.06)
model.fit(X_train)

OneClassSVM(nu=0.06)

In [35]:
y_pred_train = model.predict(X_train)

In [36]:
y_pred_test = model.predict(X_test)

In [37]:
print(classification_report(y_pred_train , y_train))

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00      3119
           1       0.94      1.00      0.97     48881

    accuracy                           0.94     52000
   macro avg       0.47      0.50      0.48     52000
weighted avg       0.88      0.94      0.91     52000

In [38]:
print(classification_report(y_pred_test , y_test))

              precision    recall  f1-score   support

          -1       0.94      0.93      0.94     26062
           1       0.93      0.95      0.94     25938

    accuracy                           0.94     52000
   macro avg       0.94      0.94      0.94     52000
weighted avg       0.94      0.94      0.94     52000

In [39]:
np.unique(y_pred_train , return_counts=True)

(array([-1,  1]), array([ 3119, 48881]))

In [40]:
np.unique(y_pred_test , return_counts=True)

(array([-1,  1]), array([26062, 25938]))